// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjjhivsdfonfyoxtyugm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqamhpdnNkZm9uZnlveHR5dWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTUzMTQsImV4cCI6MjA2ODg3MTMxNH0.KoriaeK19Xx2NBCR5s2FhMXPE5vkHurgO5WO40Vcc9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});